name: Build nightly container image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

permissions:
  contents: read
  packages: write

jobs:
  compute-suffix:
    runs-on: ubuntu-24.04
    steps:
      - id: version_vars
        env:
          TZ: Etc/UTC
        run: |
          echo truecolors_version_prerelease=nightly.$(date +'%Y-%m-%d')>> $GITHUB_OUTPUT
    outputs:
      prerelease: ${{ steps.version_vars.outputs.truecolors_version_prerelease }}

  build-image:
    needs: compute-suffix
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      cache: false
      push_to_images: |
        tootsuite/truecolors
        ghcr.io/itsallconnected/truecolors-v2
      version_prerelease: ${{ needs.compute-suffix.outputs.prerelease }}
      version_metadata: RELEASE_BUILD=true
      tags: |
        type=raw,value=${{ needs.compute-suffix.outputs.prerelease }}

  build-image-streaming:
    needs: compute-suffix
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      cache: false
      push_to_images: |
        tootsuite/truecolors-streaming
        ghcr.io/itsallconnected/truecolors-v2-streaming
      version_prerelease: ${{ needs.compute-suffix.outputs.prerelease }}
      labels: |
        org.opencontainers.image.description=Nightly build image used for testing purposes
      flavor: |
        latest=auto
      tags: |
        type=raw,value=edge
        type=raw,value=nightly
        type=schedule,pattern=${{ needs.compute-suffix.outputs.prerelease }}
    secrets: inherit





