name: Bundler Audit

on:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:
    branches:
      - 'main'
      - 'stable-*'

env:
  BUNDLE_FROZEN: false

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ./.github/actions/setup-ruby
        with:
          ruby-version: '3.2.2'

      - name: Make bundler-audit executable
        run: chmod +x bin/bundler-audit

      - name: Allow bundle modifications
        run: |
          bundle config set --local path vendor/bundle
          bundle config set --local path vendor/bundle 
          bundle install --jobs 4 --frozen

      - name: Run bundler-audit
        run: bin/bundler-audit check --update
