name: Check formatting

on:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: ./.github/actions/setup-javascript
      - name: Check formatting
        run: yarn format:check





