name: Ruby linting and static analysis

on:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:
    branches:
      - 'main'
      - 'stable-*'

env:
  BUNDLE_FROZEN: false

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ./.github/actions/setup-ruby
        with:
          ruby-version: '3.2.2'

      - name: Allow bundle modifications
        run: |
          bundle config set --local path vendor/bundle
          bundle config set --local path vendor/bundle 
          bundle install --jobs 4 --frozen

      - name: Set-up RuboCop Problem Matcher
        uses: r7kamura/rubocop-problem-matchers-action@v1

      - name: Run rubocop
        run: bin/rubocop

      - name: Run brakeman
        if: always() # Run both checks, even if the first failed
        run: bin/brakeman





