name: Normalize ALL i18n Files

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'config/locales/**/*.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  normalize-i18n:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false

      - name: Install i18n-tasks and dependencies
        run: |
          gem install i18n-tasks
          bundle config set --local path vendor/bundle
          bundle config set --local path vendor/bundle 
          bundle install --jobs 4 --frozen
          echo "i18n-tasks version: $(i18n-tasks --version)"

      - name: Check permissions on config/locales
        run: |
          ls -la config/
          ls -la config/locales/ || echo "Directory listing failed"
          chmod -R u+w config/locales/

      - name: Create i18n-tasks config if it doesn't exist
        run: |
          if [ ! -f config/i18n-tasks.yml ]; then
            echo "Creating default i18n-tasks.yml config file"
            i18n-tasks init
          fi

      - name: Normalize files using i18n-tasks directly
        run: |
          echo "Normalizing locale files with i18n-tasks..."
          i18n-tasks normalize
          echo "Normalization with i18n-tasks completed"

      - name: Verify normalization
        run: |
          echo "Verifying normalization..."
          i18n-tasks check-normalized || (echo "::warning::Some files could not be fully normalized, but continuing" && exit 0)

      - name: Check if there are changes
        id: git-check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      # For direct pushes to main
      - name: Commit changes if any (main branch)
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - i18n Normalizer"
          git add config/locales/
          git commit -m "Normalize ALL i18n YAML files [skip ci]"
          git push || echo "::warning::Failed to push changes, but workflow will continue"

      # For pull requests
      - name: Add changes to pull request
        if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - i18n Normalizer"
          git add config/locales/
          git commit -m "Normalize i18n files"
          git push
