name: Test Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'stable-*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack for Yarn version management
        run: |
          corepack enable
          # Extract Yarn version from package.json
          YARN_VERSION=$(grep -o '"packageManager": "yarn@[^"]*"' package.json | grep -o '[0-9.]*')
          echo "Project requires Yarn version: $YARN_VERSION"
          corepack prepare yarn@$YARN_VERSION --activate
          echo "YARN_ENABLE_IMMUTABLE_INSTALLS=false" >> $GITHUB_ENV

      - name: Install Babel decorator plugin
        run: yarn add --dev @babel/plugin-proposal-decorators

      - name: Install dependencies
        run: |
          bundle config set --local frozen false
          bundle add fernet || true
          bundle install --jobs 4

      - name: Fix script permissions
        run: |
          # Fix permissions on bin/*
          chmod +x bin/* || true
          # Fix normalize-all-locales.rb permission
          chmod +x normalize-all-locales.rb || true

      - name: Run Rubocop check
        run: |
          bundle exec rubocop --auto-correct || true

      - name: Run Prettier check
        run: |
          yarn install
          yarn prettier --write "**/*.{js,jsx,ts,tsx,css,scss,json,yml,yaml}" || true

  assets:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production
      NODE_ENV: production
      PRECOMPILING_ASSETS: true
      CI: true
      OTP_SECRET: ${{ secrets.OTP_SECRET }}
      # Add encryption keys
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
      # Add other essential secrets
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      # Add XMPP configuration
      XMPP_DOMAIN: ${{ secrets.XMPP_DOMAIN }}
      XMPP_BOSH_URL: ${{ secrets.XMPP_BOSH_URL }}
      XMPP_WEBSOCKET_URL: ${{ secrets.XMPP_WEBSOCKET_URL }}
      # Add CrewAI and Ollama configuration
      CREWAI_ENABLED: 'true'
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST || 'http://localhost:11434' }}
      OLLAMA_MODEL: ${{ secrets.OLLAMA_MODEL || 'phi3:mini' }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libidn11-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies for CrewAI
        run: |
          python -m pip install --upgrade pip
          pip install crewai langchain-ollama slixmpp cryptography psycopg2-binary pyyaml

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript
        with:
          onlyProduction: 'true'

      - name: Verify Yarn setup
        run: |
          # Print diagnostic information
          echo "Using Node.js version: $(node -v)"
          echo "Using Yarn from: $(which yarn)"
          echo "Yarn version: $(yarn --version)"

          # Explicitly prepare the required Yarn version from package.json if needed
          if grep -q '"packageManager"' package.json; then
            YARN_VERSION=$(grep -o '"packageManager": "yarn@[^"]*"' package.json | grep -o '[0-9][0-9.]*')
            echo "Project requires Yarn version: $YARN_VERSION"
            corepack prepare yarn@$YARN_VERSION --activate
          fi

      - name: Install Babel decorator plugin
        run: yarn add --dev @babel/plugin-proposal-decorators

      - name: Install dependencies
        run: |
          bundle config set --local frozen false
          bundle add fernet || true
          bundle install --jobs 4 --retry 3

      - name: Precompile assets
        run: |
          echo "Setting up asset precompilation environment..."
          bundle exec rake assets:precompile

  migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 3s
          --health-retries 50
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASS: postgres
      PRECOMPILING_ASSETS: true
      CI: true
      OTP_SECRET: ${{ secrets.OTP_SECRET }}
      # Add encryption keys
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
      # Add other essential secrets
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      # Add XMPP configuration
      XMPP_DOMAIN: ${{ secrets.XMPP_DOMAIN }}
      XMPP_BOSH_URL: ${{ secrets.XMPP_BOSH_URL }}
      XMPP_WEBSOCKET_URL: ${{ secrets.XMPP_WEBSOCKET_URL }}
      # Add CrewAI and Ollama configuration
      CREWAI_ENABLED: 'true'
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST || 'http://localhost:11434' }}
      OLLAMA_MODEL: ${{ secrets.OLLAMA_MODEL || 'phi3:mini' }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libidn11-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies for CrewAI
        run: |
          python -m pip install --upgrade pip
          pip install crewai langchain-ollama slixmpp cryptography psycopg2-binary pyyaml

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript

      - name: Verify Yarn setup
        run: |
          # Print diagnostic information
          echo "Using Node.js version: $(node -v)"
          echo "Using Yarn from: $(which yarn)"
          echo "Yarn version: $(yarn --version)"

          # Explicitly prepare the required Yarn version from package.json if needed
          if grep -q '"packageManager"' package.json; then
            YARN_VERSION=$(grep -o '"packageManager": "yarn@[^"]*"' package.json | grep -o '[0-9][0-9.]*')
            echo "Project requires Yarn version: $YARN_VERSION"
            corepack prepare yarn@$YARN_VERSION --activate
          fi

      - name: Install Babel decorator plugin
        run: yarn add --dev @babel/plugin-proposal-decorators

      - name: Install dependencies
        run: |
          bundle config set --local frozen false
          bundle add fernet || true
          bundle install --jobs 4 --retry 3

      - name: Run db:prepare to test migrations
        run: |
          bin/rails db:create
          bin/rails db:migrate:up VERSION=20250407100000 # Run fix_duplicate_migrations first
          bin/rails db:schema:load
          bin/rails db:migrate
